sudo: required
services:
  - docker
env:
  global:
    - REPO=leosunmo/consularis

script:
  - "./ci/build.sh"

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push $REPO
  on:
    branch: master